routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\Admin;
use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;

Route::get('test-email', function() {
    $user = new \App\Kandidate();
    $user->email = 'test-llzqdbsfw@srv1.mail-tester.com';
    Mail::to($user)
        ->send(new \App\Mail\WelcomeNotification($user));
    die('123');
});

/*******************************  Login Page  ***********************************/
Route::group(['middleware' => 'guest'], function() {
    Route::get('/',  array('as' => 'loginPage', 'uses' => 'AdminController@index'));
    Route::get('/admin/dologin',  array('as' => 'login', 'uses' => 'AdminController@login'));
    Route::get('/admin/register',  array('as' => 'register', 'uses' => 'AdminController@register'));
    Route::get('admin/forgotpassword',  array('as' => 'forgotPass', 'uses' => 'AdminController@forgotPassword'));
});

Auth::routes();

Route::get('test', function() {
    $user = \App\Kandidate::first();
    $user->email = 'work.a.andrey@gmail.com';
    Mail::to($user)
        ->send(new \App\Mail\WelcomeNotification($user));
    die('1');
});

Route::get('home', function () {
    return redirect('/admin/kandidaten');
});

Route::group(['middleware' => 'guest'], function () {
    Route::get('signup', 'PublicKandidatenController@join');
    //
    Route::post('signup', 'PublicKandidatenController@postJoin');
});

Route::get('admin/freelancers/getAllSkills', function() {
    return response()->json(['success' => true]);
});

Route::get('kandidaten/join/{code}', 'PublicKandidatenController@join')->name('candidate.public_form');
Route::post('kandidaten/join/{code}', 'PublicKandidatenController@postJoin')->name('candidate.post_join');
Route::get('signup/success', 'PublicKandidatenController@joinSuccess');

Route::group(['middleware' => 'auth'], function () {

    Route::get('/admin/search', 'DashboardController@quickSearch');

    Route::get('/dashboard', function() {
        return redirect('/admin/kandidaten');//
    });

    Route::group(['prefix' => 'dashboard'], function() {
        Route::get('/updateInfo',  array('as' => 'index', 'uses' => 'DashboardController@updateInfo'));
        Route::post('/profile/update',  array('as' => 'updateProfile', 'uses' => 'DashboardController@profileUpdate'));
    });

    Route::group(array('namespace'=>'Admin'), function() {
        Route::get('/admin/kandidaten', array('uses' => 'KandidateController@index'))->name('candidates.index');
        Route::get('admin/kandidaten/getAllFestanstellung', array('as' => 'index', 'uses' => 'KandidateController@getAllFestanstellung'));
        Route::get('admin/kandidaten/add_user', array('as' => 'add', 'uses' => 'KandidateController@addKandidateview'));
        Route::post('admin/kandidaten/add', array('uses' => 'KandidateController@addKandidate'))->name('candidates.add');
        Route::get('admin/kandidaten/{id}', array('uses' => 'KandidateController@show'))->name('candidates.view');
        Route::get('admin/kandidaten/{id}/edit', array('uses' => 'KandidateController@editKandidate'))->name('candidates.edit');
        Route::post('admin/kandidaten/{id}', array('uses' => 'KandidateController@update'))->name('candidates.update');
        Route::post('admin/kandidaten/{id}/info-text', array('uses' => 'KandidateController@updateInfoText'))->name('candidate.updateInfoText');
        Route::put('admin/kandidaten/mark/{id}', ['uses' => 'KandidateController@mark'])->name('candidates.mark');
        Route::post('admin/update_experience/{id}', array('uses' => 'KandidateController@update_experience'))->name('candidates.update_experience');
        Route::post('admin/delete_experience/{id}', array('uses' => 'KandidateController@delete_experience'))->name('candidates.delete_experience');
        Route::post('admin/add_experience/{id}', array('uses' => 'KandidateController@add_experience'))->name('candidates.add_experience');

        Route::post('admin/update_education/{id}', array('uses' => 'KandidateController@update_education'))->name('candidates.update_education');
        Route::post('admin/delete_education/{id}', array('uses' => 'KandidateController@delete_education'))->name('candidates.delete_education');
        Route::post('admin/add_education/{id}', array('uses' => 'KandidateController@add_education'))->name('candidates.add_education');
        
        Route::get('admin/kandidaten/delete/{id}', array('as' => 'delete', 'uses' => 'KandidateController@delete'));
        Route::post('admin/kandidaten{candidate}/comments', 'CandidateCommentsController@store')->name('candidates.comment-store');
        Route::delete('admin/kandidaten/comments/{id}', 'CandidateCommentsController@remove')->name('candidates.comment-remove');

        Route::group(['prefix' => 'admin'], function() {
            Route::get('kandidaten-invite', 'KandidateController@invite')->name('candidate.invite');
            Route::post('kandidaten-import-xlsx', 'KandidateController@importXlsx')->name('candidate.importXlsx');
            Route::post('kandidaten-invite', 'KandidateController@sendInvite')->name('candidate.sendInvite');

            Route::group(['prefix' => 'kandidaten'], function() {
                Route::get('{id}/activate', 'KandidateController@activate')->name('candidate.activate');
                Route::get('{id}/deactivate', 'KandidateController@deactivate')->name('candidate.deactivate');
            });
        });


        Route::get('admin/kandidaten/edit/{id}/{list}', array('as' => 'edit', 'uses' => 'KandidateController@editFestanstellung'));

        Route::post('admin/Festanstellung/sendMail', array('as' => 'index', 'uses' => 'KandidateController@openMailPanel'));

        Route::post('admin/Festanstellung/send', array('as' => 'index', 'uses' => 'KandidateController@sendMail'));

        Route::group(['middleware' => [Admin::class]], function() {
            Route::get('admin/skills/search', 'SkillsController@search')->name('skills.search');
            Route::resource('admin/skills', 'SkillsController');
            Route::get('admin/skills/{skill}/delete', 'SkillsController@destroy');
        });
        Route::post('/admin/password-change',  'KandidateController@passwordChange')
            ->name('admin.changePassword');
    });
});

app/Kandidate.php
<?php

namespace App;

use App\Models\Comment;
use Illuminate\Database\Eloquent\Model;

class Kandidate extends Model
{
    protected $fillable = [
        'title',
        'first_name',
        'email',
        'hourly_rate',
        'role_definition',
        'general_notes',
        'category_skills',
        'availability_per_week',
        'password',
        'travelling',
        'traveling_state',
        'traveling_city',
        'availability_per_week_en'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $table = "kandidates";

    const HOURLY_RATES = [
        //            "1" => "20.000 EUR - 30.000 EUR",
        "2" => "30.000 EUR - 40.000 EUR",
        "3" => "40.000 EUR - 50.000 EUR",
        "4" => "50.000 EUR - 60.000 EUR",
        "5" => "60.000 EUR - 70.000 EUR",
        "6" => "70.000 EUR - 80.000 EUR",
        "7" => "80.000 EUR - 90.000 EUR",
        "8" => "90.000 EUR - 100.000 EUR",
        "9" => "100.000 EUR - 110.000 EUR",
        "10" => "110.000 EUR - 120.000 EUR",
        "11" => "120.000 EUR +"
    ];

    const AVAILABILITY = [
        "1" => "A1",
        "2" => "A2",
        "3" => "B1",
        "4" => "B2",
        "5" => "C1",
        "6" => "C2"
    ];

    const HOURLY_RATES_SHORT = [
        1 => '20-30K',
        2 => '30-40K',
        3 => '40-50K',
        4 => '50-60K',
        5 => '60-70K',
        6 => '70-80K',
        7 => '80-90K',
        8 => '90-100K',
        9 => '100-110K',
        10 => '110-120K',
        11 => '120+K'
    ];

    const ROLES = [
        "1" => "Entwickler",
        "2" => "Architekt",
        "3" => "Support",
        "4" => "Projektmanager",
        "5" => "Berater",
        "6" => "Administrator",
        "7" => "SCRUM Master",
        "8" => "Tester",
        "9" => "Test Manager",
        "10" => "Hardware Entwickler",
        "11" => "Web Developer",
        "12" => "Security",
        "13" => "Frontend",
        "14" => "Backend"
    ];

    const EDUCATION_ITEMS = [
        'Bachelor',
        'Master',
        'Diplom',
        'Doktor',
        'Fachhochschule',
        'Ausbildung',
        'Fortbildung'
    ];

    const WORK_EXPERIENCE_SECTORS = [
        'Automobilindustrie',
        'Baugewerbe',
        'Bergbau',
        'Biotechnologie',
        'Chemische Stoffe',
        'Dienstleistungsbranche',
        'Elektrische Geräte',
        'Energieversorgung',
        'Energiewirtschaft',
        'Erziehung und Unterricht',
        'Finanz- und Versicherungsdienstleister',
        'Gesundheits- und Sozialwesen',
        'Grundstücks- und Wohnungswesen',
        'Handel',
        'Hotel und Gastronomie',
        'IT-Branche',
        'Kosmetika',
        'Kunst, Unterhaltung und Erholung',
        'Land- und Forstwirtschaft, Fischerei',
        'Lebensmittelindustrie',
        'Logistikbranche',
        'Luft- und Raumfahrt',
        'Medizintechnik',
        'Pharmabranche',
        'Öffentliche Verwaltung',
        'Schiffbau und Meerestechnik',
        'Spielzeugbranche',
        'Telekommunikationsbranche',
        'Textil- und Bekleidungsbranche',
        'Verkehr und Lagerei',
        'Wasser, Abwasser und Entsorgung',
    ];

    const LINGUISTIC_PROFICIENCY = ['', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2'];

    const POSSIBLE_LOCATIONS = ['', 'Weltweit', 'Europaweit', 'Deutschlandweit', 'Bundesland', 'Stadt'];

    public function getRolesAttribute()
    {
        return collect(explode(',', $this->role_definition))->filter(
            function ($i) {
                return is_numeric($i);
            }
        )->map(
            function ($roleId) {
                return static::ROLES[$roleId];
            }
        );
    }

    public function getSalaryExpectationsAttribute()
    {
        return collect(explode(',', $this->hourly_rate))->filter(
            function ($i) {
                return is_numeric($i);
            }
        )->map(
            function ($hourlyRateId) {
                return static::HOURLY_RATES_SHORT[$hourlyRateId];
            }
        );
    }

    public function getLinguisticProficiencyAttribute()
    {
        return collect(explode(',', $this->availability_per_week))->filter(
            function ($i) {
                return is_numeric($i);
            }
        )->map(
            function ($item) {
                return static::LINGUISTIC_PROFICIENCY[$item];
            }
        );
    }

    public function getSkillsAttribute()
    {
        $skills = \DB::table('competences_skill')->select('id', 'skill')->get()->keyBy('id');
        return collect(explode(',', $this->category_skills))->filter(
            function ($i) {
                return is_numeric($i);
            }
        )->map(
            function ($skillId) use ($skills) {
                return $skills[$skillId]->skill;
            }
        );
    }

    public function getCompetencesAttribute()
    {
        $skills = \DB::table('competences_skill')->select('id', 'skill')->get()->keyBy('id');
        return collect(explode(',', $this->category_skills))->filter(
            function ($i) {
                return is_numeric($i);
            }
        )->map(
            function ($skillId) use ($skills) {
                return $skills[$skillId]->skill;
            }
        );
    }

    public function getPossibleLocationAttribute()
    {
        $candidate = $this;
        return collect(explode(',', $this->travelling))->filter(
            function ($i) {
                return is_numeric($i);
            }
        )->map(
            function ($location) use ($candidate) {
                $appendix = '';
                if ($location == 4 && !empty($candidate['traveling_state'])) {
                    $appendix = " - {$candidate['traveling_state']}";
                } elseif ($location == 5 && !empty($candidate['traveling_city'])) {
                    $appendix = " - {$candidate['traveling_city']}";
                }
                return Kandidate::POSSIBLE_LOCATIONS[$location].$appendix;
            }
        );
    }

    public function getLinguisticProficiencyEnAttribute()
    {
        $candidate = $this;
        return collect(explode(',', $candidate['availability_per_week_en']))->filter(
            function ($i) {
                return is_numeric($i);
            }
        )->map(
            function ($item) {
                return Kandidate::LINGUISTIC_PROFICIENCY[$item];
            }
        );
    }

    public function getEducationListAttribute()
    {
        $candidate = $this;
        return collect(explode(',', $candidate['education']))->filter(
            function ($i) {
                return is_numeric($i);
            }
        )->map(
            function ($item) {
                return Kandidate::EDUCATION_ITEMS[$item];
            }
        );
    }


    public function comments()
    {
        return $this->hasMany(Comment::class, 'user_id');
    }
}

resources/views/freelancer_profile.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">Profil</h3>
                </div>
                <div>
                </div>
            </div>
        </div>
        <!-- END: Subheader -->
        <div class="m-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <div class="m-portlet__head">
                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
											<span class="m-portlet__head-icon m--hide">
											<i class="la la-gear"></i>
											</span>
                                    <h3 class="m-portlet__head-text">
                                        Profil
                                    </h3>
                                </div>
                            </div>
                        </div>
                        <!--begin::Form-->
                        <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed"
                              name="edit_freelancer" id="edit_freelancer">
                            {{ csrf_field() }}
                            <div class="m-portlet__body">
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-4 col-form-label text-left">Name</label>
                                    <div class="col-lg-6">
                                        <input type="hidden" id="user_id" name="user_id" value="{{$user->id}}">
                                        <input type="text" name="name" id="" class="form-control m-input"
                                               placeholder="Name" value="{{$user->first_name}}">
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-4 col-form-label text-left">Email</label>
                                    <div class="col-lg-6">
                                        <input type="email" name="email" id="email" class="form-control m-input"
                                               placeholder="Email" value="{{$user->email}}" required="">
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-4 col-form-label text-left">Telefonnummer.</label>
                                    <div class="col-lg-6">
                                        <input type="text" name="phone" id="phone" class="form-control m-input"
                                               placeholder="Telefonnummer." value="{{$user->Mobile}}">
                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                                <div class="m-form__actions m-form__actions--solid">
                                    <div class="row">
                                        <div class="col-lg-5"></div>
                                        <div class="col-lg-7">
                                            <button type="submit" id="edit_profile" name="edit_profile"
                                                    class="btn btn-brand">Aktualisieren
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/show.blade.php
@extends('layouts.candidates')
@section('template')
    <style>
        .m-content > div > form {
            display: none !important;
        }
        .m-content.admin-content h4{
            font-family: "Avenir-Heavy" !important;
            font-size: 32px;
            color: #434656;
        }        
        .m-content.admin-content{
            font-family: "Avenir-Roman";
        }
        .candidate-profile {
            margin-bottom: 30px;
        }
        .candidate-profile .profile-details {
            padding: 10px;
            border: 1px solid #ddd;
            border-top: 0;
            height: 250px;
        }
        .box-container {
            padding: 15px;
            border-radius: 5px;
            background: #fff;
            margin-top: 20px;
            margin-bottom: 15px;
        }
        .box-container > span{
            font-size: 22px;
            color: #3D4564;
        }
        .admin-content {
            padding: 0px 0px !important;
        }
        .top-section {
            background: linear-gradient(to top,#0074E4,#5867DD);
            padding-top: 80px;
        }
        .top-section .row{
            background: #fff;
        }
        .m-subheader {
            position: absolute;
            left: 0;
            right: 0;
            width: 100%;
            max-width: 1140px;
            display: block;
            padding-top: 0px;
            margin: 0 auto;
            padding-left: 0px !important;
        }
        .mr-auto {
            margin-top: 15px;
            margin-left: 10px;
        }
        #candidates .col-md-4{
            padding-left: 0;
        }
        .box-skills{
            font-size: 16px;
        }
        .sector{
            font-size: 12px;
            color: #7A7B81;
            text-transform: uppercase; 
        }
        .period{
            font-size: 12px;
            text-align: right;
            color: #7A7B81;
            margin-right: 20px;
            float: right;
        }
        .hf div{
            display: inline-block;
        }
        .com-name{
            font-size: 22px;
            color: #FF7B7D;
        }
        .exp-position{
            display: inline-block;
            padding: 5px 15px;
            box-shadow: 0 2px 2px rgba(0,0,0,.1);
            border-radius: 20px;
        }
        .box-container > span.lang{
            color: #FF7B7D;
            font-size: 20px;
        }
        .box-container > span.lang-class{
            font-size: 16px;
        }
        .profile-head-box{
            background: #007BE5;
            display: inline-block;
            border-radius: 5px;
            margin-top: 20px;
        }
        
        .profile-head-box > div{
            display: inline-block;
            text-align: center;
            padding: 10px 20px;
            min-width: 175px;
        }
        .gehal-box{
            color: #fff;
        }
        .head-lang-box{
            border: 1px solid #0074E4;
            background: #fff;
        }
        .head-lang  p{
            font-size: 16px;
        }
        .btn.btn-danger {
            background: #007BE5;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            padding: 15px 65px;
        }        
        .btn.btn-danger span > span {
            padding-left: 0;
        }
        .Verfugbarkeit-info {
            background: rgba(86,104,222,.7);
            color: #fff;
            font-size: 16px;
            display: inline-block;
            padding: 5px 10px;
            border-radius: 20px;
            margin-top: 40%;
        }
        .Verfugbarkeit-yes{
            color: #28C195;
            font-size: 12px;
            vertical-align: text-bottom;
            margin-right: 10px;
            margin-left: 5px;
        }
        .no{
            font-weight: bold;
            color: #FF7B7D !important;
            font-size: 16px !important;
        }
        .yes{
            font-weight: bold;
            color: #28C195 !important;
            font-size: 16px !important;
        }
        .mr-auto {
            margin-left: 0px;
        }
        .m-page-title{
            color: #fff;
            background: #8895E8;
            padding: 5px 20px;
            border-radius: 20px;
        }
        .top-section .box-container{
            text-align: center;
        }
        .mob-center{
            text-align: center;
        }
        @media (min-width: 768px){
            .col-md-8{
                padding-right: 0 !important 
            }
            .col-md-4{
                padding-left: 0 !important
            }
        }
    </style>

    <div class="m-content admin-content">
        <div class="m-portlet m-portlet--mobile bg-admin">
            <div class="m-portlet__body">
                @if (Session::has('user_message'))
                    <div class="m-alert m-alert--outline alert alert-info alert-dismissible fade show"
                         role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        {{Session::get('user_message')}}
                    </div>
                @endif
                <div class="top-section">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                        <img src="{{!empty($candidate->picture) ? '/public/uploads/' . $candidate->picture : '/no-photo.jpg'}}" alt="" style="width: 100%">
                        </div>
                        <div class="col-md-8">
                         <div class="box-container mob-center">
                            <div class="row">
                                <div class=" col-md-12 col-lg-8">
                                                             <h4>{{$candidate->first_name}} - {{$candidate->optional_interview}}</h4>
                                <div style="font-size: 18px !important;;">
                                    {{$candidate->roles->implode(', ')}}
                                </div>
                                <div class="profile-head-box">
                                <div class="gehal-box"><span> Gehaltsvorstellung</span> <br>  <span class="gehal">{{$candidate->salaryExpectations->implode(', ')}}; </span></div>
                                <div class="head-lang-box">
                                <span>Sprachen<br></span>
                                    <span>{{$candidate->linguisticProficiency->implode(', ')}}.</span>
                                </div>     
                                </div>
                                </div>
                                <div class=" col-md-12 col-lg-4">
                                    <div class="row">
                                        <div class="col-xs-6">
                                   <form action="{{url('admin/Festanstellung/sendMail')}}" id="festanstellung_send" method="POST"
                          target="_blank">
                        {{ csrf_field() }}
                        <input type="hidden" name="festanstellung_id" id="festanstellung_id">

                        <button type="submit" class="btn btn-danger m-btn m-btn--icon" id="festanstellung_Send_mail">
                                <span>
                                    <span>
                                        Send Mail
                                    </span>
                                </span>
                        </button>
                                    </form>
                                </div>
                                <div class="col-xs-6">
                                    <div class="Verfugbarkeit-info">
                                        <span class="Verfugbarkeit-yes">&#11044;</span>Verfügbarkeit bestätigt
                                    </div>
                                    </div>  
                                </div>
                              </div>
                            </div>

                            </div>   
                        </div>
                    </div>
                </div>
                </div>
                <div class="container">
                    <div class="row" id="candidates">
                        <div class="col-md-4">
                            <div class="box-container box-skills">
                                <span style="font-weight: bold">
                                    Technische Fähigkeiten
                                </span>
                                <p></p><br>{!! $candidate->skills->implode('<hr>') !!}</br>
                                
                            </div>
                            <div class="box-container box-skills">
                                <span style="font-weight: bold">
                                    Core Competences
                                </span>
                                <p></p><br>{!! $candidate->competences->implode('<hr>') !!}</br>
                            </div>
                            <div class="box-container box-skills">
                                <span style="font-weight: bold">
                                    Other interviews and offers:
                                </span>
                               <span class="no">{!! $candidate->other_interview ? $candidate->comment_area_text : 'No' !!}</span>
                            </div>
                            <div class="box-container box-skills">
                                <span style="font-weight: bold">
                                    References Details:
                                </span>
                                <span class="no">{{$candidate->client_name}}</span>
                            </div>
                            @if(Auth::user()->isAdmin)
                            <div class="box-container">
                                <span style="font-weight: bold">
                                    Is confirmed?
                                </span>
                                <span class="no">{!! $candidate->is_confirmed ? 'Yes' : 'No' !!}</span>
                            </div>
                            <div class="box-container">
                                <span style="font-weight: bold">
                                    Is active?
                                </span>
                                <span class="no">{!! $candidate->is_active ? 'Yes' : 'No' !!}</span>
                            </div>
                            @endif
                        </div>
                        <div class="col-md-8">
                            <div class="box-container">
                                <span style="font-weight: bold">in aller Kürze über mich</span>
                                <p></p>
                                <div>{!! nl2br($candidate->general_notes) !!}</div>
                            </div>
                            <div class="box-container">
                                <span style="font-weight: bold">Möglicher Arbeitsort:</span>
                                <p></p>{!! $candidate->possibleLocation->implode(',<br> ') !!}
                            </div>
                            <div class="box-container">
                                <span style="font-weight: bold">Berufserfahrung</span>
                                <br>
                                <div class="hf">
                                <div class="sector">{{\App\Kandidate::WORK_EXPERIENCE_SECTORS[$candidate->work_experience_sector]}}</div>
                                <div class="period">{{$candidate->work_experience_period}}</div>   
                                </div>
                                <br>
                                <div class="com-name">{{$candidate->work_experience_company_name}}</div>
                                <br>
                                <div class="exp-position">@php $roles = \App\Kandidate::ROLES; @endphp
                                {{isset($roles[$candidate->work_experience_position]) ? $roles[$candidate->work_experience_position] : ''}}</div>
                                <br>
                                <br>
                                <div class="prof-experience">{!! $candidate->work_experience_position_description !!}</div>
                            </div>
                            <div class="box-container">
                                <span style="font-weight: bold">Ausbildung, Universität und Abschlüsse</span>
                                <br>
                                {{$candidate->educationList->implode(', ')}}
                            </div>
                            <div class="box-container">
                                <span style="font-weight: bold">Languages:</span>
                                <p></p>
                                <span class="lang">Deutsch:</span><br><span class="lang-class">{{$candidate->linguisticProficiency->implode(', ')}}</span>
                                <hr>
                                <span class="lang">English</span><br><span class="lang-class">{{$candidate->linguisticProficiencyEn->implode(', ')}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')

@endsection