typo3_grau_04/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\Admin;
use App\User;
use Illuminate\Support\Facades\Hash;

/*******************************  Login Page  ***********************************/
Route::group(['middleware' => 'guest'], function() {
    Route::get('/',  array('as' => 'loginPage', 'uses' => 'AdminController@index'));
    Route::get('/admin/dologin',  array('as' => 'login', 'uses' => 'AdminController@login'));
    Route::get('/admin/register',  array('as' => 'register', 'uses' => 'AdminController@register'));
    Route::get('admin/forgotpassword',  array('as' => 'forgotPass', 'uses' => 'AdminController@forgotPassword'));
});

Auth::routes();

Route::get('admin/freelancers/getAllSkills', function() {
    return response()->json(['success' => true]);
});

Route::get('kandidaten/join/{code}', 'PublicKandidatenController@join')->name('candidate.public_form');
Route::post('kandidaten/join/{code}', 'PublicKandidatenController@postJoin')->name('candidate.post_join');
Route::get('kandidaten/join-success', 'PublicKandidatenController@joinSuccess');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', function() {
        return redirect('/admin/kandidaten');
    });

    Route::group(['prefix' => 'dashboard'], function() {
        Route::get('/updateInfo',  array('as' => 'index', 'uses' => 'DashboardController@updateInfo'));
        Route::post('/profile/update',  array('as' => 'updateProfile', 'uses' => 'DashboardController@profileUpdate'));
    });

    Route::group(array('namespace'=>'Admin'), function() {
        Route::group(['prefix' => 'admin'], function() {
            Route::resource('projects', 'ProjectController');
            Route::get('comments/{comment}/delete', 'CandidateCommentsController@destroy');

            Route::group(['prefix' => 'kandidaten'], function () {
                Route::get('{candidate}/comments', 'CandidateCommentsController@show')->name('candidates.comments');
                Route::post('{candidate}/comments', 'CandidateCommentsController@store')->name('candidates.comment-store');

                Route::get('/', array('uses' => 'KandidateController@index'))->name('candidates.index');
                Route::get('getAllFestanstellung', array('as' => 'index', 'uses' => 'KandidateController@getAllFestanstellung'));
                Route::get('add_user', array('as' => 'add', 'uses' => 'KandidateController@addKandidateview'));
                Route::post('add', array('uses' => 'KandidateController@addKandidate'))->name('candidates.add');
                Route::get('{id}', array('uses' => 'KandidateController@show'))->name('candidates.view');
                Route::get('{id}/edit', array('uses' => 'KandidateController@editKandidate'))->name('candidates.edit');
                Route::post('{id}', array('uses' => 'KandidateController@update'))->name('candidates.update');
                Route::get('delete/{id}', array('as' => 'delete', 'uses' => 'KandidateController@delete'));
                Route::get('{id}/activate', 'KandidateController@activate')->name('candidate.activate');
                Route::get('{id}/deactivate', 'KandidateController@deactivate')->name('candidate.deactivate');
            });

            Route::get('kandidaten-invite', 'KandidateController@invite')->name('candidate.invite');
            Route::post('kandidaten-invite', 'KandidateController@sendInvite')->name('candidate.sendInvite');

        });


        Route::get('admin/kandidaten/edit/{id}/{list}', array('as' => 'edit', 'uses' => 'KandidateController@editFestanstellung'));

        Route::post('admin/Festanstellung/sendMail', array('as' => 'index', 'uses' => 'KandidateController@openMailPanel'));

        Route::post('admin/Festanstellung/send', array('as' => 'index', 'uses' => 'KandidateController@sendMail'));

        Route::group(['middleware' => [Admin::class]], function() {
            Route::resource('admin/skills', 'SkillsController');
            Route::get('admin/skills/{skill}/delete', 'SkillsController@destroy');
        });
        Route::post('/admin/password-change',  'KandidateController@passwordChange')
            ->name('admin.changePassword');
    });
});

typo3_grau_04/resources/views/employee/index.blade.php
<!DOCTYPE html>
<html lang="en" >
	<!-- begin::Head -->
	<head>
		<meta charset="utf-8" />
		<title>
			Argon | Employees
		</title>
		@extends('layouts.admin_dashboard')
		@section('content')
				<div class="m-grid__item m-grid__item--fluid m-wrapper">
					<!-- BEGIN: Subheader -->
					<div class="m-subheader ">
						<div class="d-flex align-items-center">
							<div class="mr-auto">
								<h3 class="m-page-title">
									Home / Employees
								</h3>
							</div>
						</div>
					</div>
					@if (session('status'))
					<div class="alert alert-success alert-dismissible fade show" role="alert" style="display: block; padding: 10px; margin:27px;">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
					<p class="message">
    							{{session('status')}}
								 </p>
					</div>@endif
					<!-- END: Subheader -->
					<div class="m-content">
						<div class="m-portlet m-portlet--mobile">
							<div class="m-portlet__body">
								<!--begin: Search Form -->
								<div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
									<div class="row align-items-center">
										<div class="col-xl-8 order-2 order-xl-1">
											<div class="form-group m-form__group row align-items-center">
												<div class="col-md-6">
													<div class="m-form__group m-form__group--inline">
														<div class="m-form__label">
															<label>
																Employees:
															</label>
														</div>
														<div class="m-form__control">
															<select class="form-control m-bootstrap-select m-bootstrap-select--solid" id="m_form_status">
																<option value="">
																	All Employees
																</option>
															</select>
														</div>
													</div>
													<div class="d-md-none m--margin-bottom-10"></div>
												</div>
												<div class="col-md-4">
													<div class="m-input-icon m-input-icon--left">
														<input type="text" class="form-control m-input m-input--solid" placeholder="Search..." id="generalSearch">
														<span class="m-input-icon__icon m-input-icon__icon--left">
															<span>
																<i class="la la-search"></i>
															</span>
														</span>
													</div>
												</div>
											</div>
										</div>
										<div class="col-xl-4 order-1 order-xl-2 m--align-right">
											<a href="" class="btn m-btn--pill btn-success" data-toggle="modal" data-target="#addEmployee">
												<span>
													<i class="m-menu__link-icon flaticon-user-add"></i>
													<span>
														ADD NEW EMPLOYEE
													</span>
												</span>
											</a>
											<div class="m-separator m-separator--dashed d-xl-none"></div>
										</div>
									</div>
								</div>
								<!--end: Search Form -->
								<!--begin: Datatable -->
								<div class="loader_msg" style='display: block;'>
									<img src="../assets/app/media/img/logos/loader.gif" width='132px' height='132px' style="height: 70px;width: 67px;margin-left: 40%;">
								</div>
								<div class="m_datatable" id="local_data">
								</div>

								<!--end: Datatable -->
							</div>
						</div>
					</div>
					
				</div>
			</div>
			<!-- end:: Body -->
<div id="addEmployee" class="modal fade" role="dialog">
	<div class="modal-dialog" style="width: 50%;">
	<!-- Modal content-->
		<div class="modal-content">
		  	<div class="modal-header">
			    <!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
		    <h4 class="modal-title">Add New Employee</h4>
		  	</div>
		  	<div class="modal-body">
									<!--begin::Form-->
			<form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" id="addemployee" name="addemployee">
			{{ csrf_field() }}
				<div class="m-portlet__body">
					<div class="form-group m-form__group row">
						<div class="col-lg-6">
							<label>
								First Name *:
							</label>
							<input type="text" name="first_name" id="first_name" class="form-control m-input" placeholder="Enter First name Minimum 3 characters">
                                <div class="error_msg">
                                	<span class="first_name"></span>
                                </div>
						</div>
						<div class="col-lg-6">
							<label>
								Last Name *:
							</label>
							<input type="text" name="last_name" id="last_name" class="form-control m-input" placeholder="Enter Last name Minimum 3 characters">
                                <div class="error_msg">
                                	<span class="last_name"></span>
                                </div>
						</div>
					</div>
					<div class="form-group m-form__group row">
						<div class="col-lg-6">
							<label>
								Email Id *:
							</label>
							<input type="text" name="employee_email" id="employee_email" class="form-control m-input" placeholder="Enter Email Id of Employee">
                                <div class="error_msg">
                                	<span class="employee_email"></span>
                                </div>
						</div>
						<div class="col-lg-6">
							<label>
								Password *:
							</label>
							<input type="password" name="employee_password" id="employee_password" class="form-control m-input" placeholder="Enter Password">
                                <div class="error_msg">
                                	<span class="employee_password"></span>
                                </div>
						</div>
					</div>
				</div>
				<div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
					<div class="m-form__actions m-form__actions--solid">
						<div class="row">
							<div class="col-lg-4"></div>
							<div class="col-lg-8">
								<button type="submit" id="m_signup_employee" name="m_signup_employee" class="btn btn-primary">
									Submit
								</button>
								<button type="reset" class="btn btn-secondary" data-dismiss="modal">
									Cancel
								</button>
							</div>
						</div>
					</div>
				</div>
			</form>
			<!--end::Form-->
	  		</div>
		</div>
	</div>
</div>
	<!-- end::Quick Sidebar -->		    
    <!-- begin::Scroll Top -->
	<div class="m-scroll-top m-scroll-top--skin-top" data-toggle="m-scroll-top" data-scroll-offset="500" data-scroll-speed="300">
		<i class="la la-arrow-up"></i>
	</div>
	<!-- end::Scroll Top -->
	@endsection
	@section('js')
    <script src="{{asset('/js/employee.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
    	$('#employee_link').addClass('m-menu__item--active');
    </script>
	@endsection

typo3_grau_04/resources/views/layouts/admin_dashboard.blade.php
@include('admin_dashboard_template.admin_header')
@include('admin_dashboard_template.admin_content')
@yield('content')
@include('admin_dashboard_template.admin_footer')
@yield('css')
@yield('js')

typo3_grau_04/resources/views/layouts/admin_pages.blade.php
@include('pages_template.admin_header')
@include('pages_template.admin_content')
@yield('content')
@include('pages_template.admin_footer')
@yield('css')
@yield('js')

typo3_grau_04/resources/views/layouts/candidates.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>
        Argon | Festanstellung
    </title>
    @extends('layouts.admin_dashboard')
    @section('content')
        <style>
            .m-datatable__table th {
                font-size: 16px !important;
            }
            .displayb >label {
                font-size: 16px !important;
            }
            .m-datatable__cell{
                background: #fff
            }
        </style>
        <!-- END: Left Aside -->
        <div class="m-grid__item m-grid__item--fluid m-wrapper admin-index">
            <!-- BEGIN: Subheader -->
            <div class="m-subheader " style="display: block;">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="m-page-title" style="height: auto;">
                            Home / Festanstellung
                        </h3>
                    </div>
                    @if(Auth::user()->isAdmin)
                        <a href="{{url('admin/kandidaten/add_user')}}" class="btn btn-primary m-btn m-btn--icon"
                       id="add_user" style="position: relative;top: -5px;">
                                <span>
                                    <span>Kandidaten Hinzufügen</span>
                                </span>
                        </a>
                        @if(Auth::user()->isAdmin)
                        <a href="{{route('projects.index')}}" class="btn btn-warning m-btn m-btn--icon" style="position: relative;top: -5px; margin-left: 10px;">
                            <span><span>Projekte</span></span>
                        </a>
                        @endif
                        @if(request()->route()->parameter('id') > 0)
                            <a href="/admin/kandidaten/{{request()->route()->parameter('id')}}/edit" class="btn btn-success m-btn m-btn--icon" style="position: relative;top: -5px; margin-left: 10px;">
                                <span><span>Edit</span></span> 
                            </a>
                        @endif
                    @endif
                </div>
            </div>
            <div class="m-content" style="position: relative; padding: 0 30px; margin-left: 0%">
                <div class="text-right">
                    <form action="{{url('admin/Festanstellung/sendMail')}}" id="festanstellung_send" method="POST"
                          target="_blank">
                        {{ csrf_field() }}
                        <input type="hidden" name="festanstellung_id" id="festanstellung_id">

                        <button type="submit" class="btn btn-danger m-btn m-btn--icon" id="festanstellung_Send_mail">
								<span>
									<span>
										Send Mail
									</span>
								</span>
                        </button>
                    </form>
                </div>
            </div>

            <!-- END: Subheader -->
            @yield('template')

        </div>
        </div>
        <!-- end:: Body -->
        <!-- begin::Quick Sidebar -->
        <div id="m_quick_sidebar" class="m-quick-sidebar m-quick-sidebar--tabbed m-quick-sidebar--skin-light">
            <div class="m-quick-sidebar__content m--hide">
        <span id="m_quick_sidebar_close" class="m-quick-sidebar__close">
          <i class="la la-close"></i>
        </span>
                <ul id="m_quick_sidebar_tabs" class="nav nav-tabs m-tabs m-tabs-line m-tabs-line--brand comment_div"
                    role="tablist">
                    <!-- Form area -->
                    <li>
                        <h3>Leave Comment </h3><br>
                        <input type="hidden" id="auth_id" value="{{Auth::id()}}">
                    </li>
                    <li>
                    <li>
                        <label for="comment_area">
                            Comment :
                        </label>
                        <textarea class="form-control" id="comment_area" name="comment_area" rows=5></textarea>
                    </li>
                    <!-- End form area -->

                </ul>
                <div class="form-group">
                    <button type="button" class="btn btn-success" id="LeaveComment">Submit</button>
                    <button type="button" class="btn btn-default" id="CancelComment">Cancel</button>
                </div>
            </div>
        </div>
        <!-- end::Quick Sidebar -->
        <!-- begin::Scroll Top -->
        <div class="m-scroll-top m-scroll-top--skin-top" data-toggle="m-scroll-top" data-scroll-offset="500"
             data-scroll-speed="300">
            <i class="la la-arrow-up"></i>
        </div>
        <!-- end::Scroll Top -->            <!-- begin::Quick Nav -->

        <!-- begin::Quick Nav -->
        <!-- begin : CSV modal -->
        <div id="ImportCSV" class="modal fade" role="dialog">
            <div class="modal-dialog" style="width: 40%;">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">CSV upload form</h4>
                    </div>
                    <div class="modal-body">
                        <!-- Form -->
                        <form method="post" action="{{url('admin/freelancers/csv')}}" name="upload_file"
                              id="upload_file" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            Select file : <input type='file' name='attach_csv' id='attach_csv1' class='form-control'
                                                 required=""><br>
                            <span id="errormessage"></span>
                            <p style="color: red">* Download Sample File from <a
                                        href="{{url('admin/freelancers/csvexport')}}" id="Exportcsv">here</a></p>
                            <p style="color: red">* Please Select Only CSV format</p>
                            <button class="btn btn-primary" id="upload1" name="upload" type="submit">Upload</button>
                        </form>
                    </div>

                </div>

            </div>
        </div>
    @endsection
@section('js')
    <!-- <script src="{{url('assets/demo/default/custom/components/datatables/base/data-freelancers.js')}}" type="text/javascript"></script> -->
        <link rel="stylesheet" type="text/css" href="../../css/typeahead.css">
             
        <script src="{{asset('/js/autocomplete.js')}}" type="text/javascript"></script>
        <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-autocomplete/1.0.7/jquery.auto-complete.min.js" type="text/javascript"></script> -->
        <script type="text/javascript">
            @if(session()->has('status'))
            swal('Success', '{{session('status')}}', 'success');
            @endif
            var categorySkills = {!! json_encode(collect($skills)->keyBy('id')) !!};
            $('#contact_link').addClass('m-menu__item--active m-menu__item--expanded m-menu__item--open');
            $('#freelancer_link').addClass('m-menu__item--active');
            var datatable;
            var dataWithKey = {
                '1': '20-30K',
                '2': '30-40K',
                '3': '40-50K',
                '4': '50-60K',
                '5': '60-70K',
                '6': '70-80K',
                '7': '80-90K',
                '8': '90-100K',
                '9': '100-110K',
                '10': '110-120K',
                '11': '120+K'
            };

            $(document).ready(function () {
                $('#festanstellung_send').hide();

                $(".festanstellung_datatable").on('change', '.send_mail', function () {

                    //alert('Hello Argon');
                    var checkbox_val = $(this).find(':first-child').val();
                    //alert(checkbox_val);

                    var selected = '';
                    //alert(selected);
                    $("input:checkbox:checked").each(function () {
                        if ($(this).val() != 'on') {
                            selected += $(this).val() + ',';
                        }
                    });

                    // $("#btnSend").attr('href', 'mailto:'+selected.slice(0, -1));

                    if (selected.slice(0, -1) != '') {
                        $('#festanstellung_send').show();
                        $('#festanstellung_id').val(selected.slice(0, -1));
                        console.log(selected.slice(0, -1));
                    }
                    else {
                        $('#festanstellung_send').hide();
                    }

                });

                $('[data-toggle="popover"]').popover();

                $('.loader_msg').css('display','none');
                $('.candidate-profile').show();
            });
        </script>

        <script type="text/javascript" src="/vue.js"></script>
        <script type="text/javascript" src="/candidates.js"></script>
@endsection

typo3_grau_04/resources/views/layouts/dashboard.blade.php
@include('template_parts.freelancer_header')
@include('template_parts.freelancer_content')
@yield('content')
@include('template_parts.freelancer_footer')
@yield('css')
@yield('js')

typo3_grau_04/resources/views/projects/_form.blade.php
{{ csrf_field() }}
<style>
    .has-error input {
        border-color: red;
    }
    .has-error .help-block {
        color: red;
    }
</style>
<div class="m-portlet__body">
    <div class="form-group m-form__group row{{ $errors->has('name') ? ' has-error' : '' }}">
        <label class="col-lg-4 col-form-label text-left">
            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Name</font></font>
        </label>
        <div class="col-lg-8 ref_input">
            <input type="text" name="name" id="name" class="form-control m-input"
                   placeholder="Enter Project Name" value="{{old('name', $project->name)}}" required autofocus>
            @if ($errors->has('name'))
                <span class="help-block">
                   <strong>{{ $errors->first('number') }}</strong>
               </span>
            @endif
        </div>
    </div>

    <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
        <div class="m-form__actions m-form__actions--solid">
            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-8">
                    <a class="btn btn-secondary pull-right" href="{{ route('projects.index') }}">Cancel</a>
                    <button type="submit" class="btn btn-primary pull-right" style="margin-right: 20px;">
                        @if($project->id)
                            Update
                        @else
                            Add
                        @endif
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

typo3_grau_04/resources/views/projects/create.blade.php
<!DOCTYPE html>
<html lang="en">
<!-- begin::Head -->
<head>
    <meta charset="utf-8"/>
    <title>
        Argon | Festanstellung
    </title>
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__rendered .select2-search__field {
            width: 125px !important;
        }
        .m-grid.m-grid--ver-desktop.m-grid--desktop > .m-grid__item.m-grid__item--fluid {
            flex: none !important;
            width: 80%;
        }
    </style>
@extends('layouts.admin_dashboard')
@section('content')
    <!-- END: Left Aside -->
        <div class="m-grid__item m-grid__item--fluid m-wrapper">
            <!-- BEGIN: Subheader -->
            <div class="m-subheader">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="m-page-title ">
                            <a href="{{ url('/admin/projects')}}">Projects</a>
                        </h3>
                    </div>
                </div>
            </div>
            @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert"
                     style="display: block; padding: 10px; margin:27px;">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                    <p class="message">
                        {{session('status')}}
                    </p>
                </div>@endif
            <div class="m-portlet m-portlet--rounded view_block">
                <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" method="post"
                      action="{{route('projects.store')}}"
                      enctype="multipart/form-data">
                    @include('projects._form')
                </form>
            </div>
            <!-- end:: Body -->
            <!-- begin::Scroll Top -->
            <div class="m-scroll-top m-scroll-top--skin-top" data-toggle="m-scroll-top" data-scroll-offset="500"
                 data-scroll-speed="300">
                <i class="la la-arrow-up"></i>
            </div>
        </div>
        <!-- end::Scroll Top -->
@endsection

typo3_grau_04/resources/views/projects/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<!-- begin::Head -->
<head>
    <meta charset="utf-8"/>
    <title>
        Argon | Festanstellung
    </title>
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__rendered .select2-search__field {
            width: 125px !important;
        }
        .m-grid.m-grid--ver-desktop.m-grid--desktop > .m-grid__item.m-grid__item--fluid {
            flex: none !important;
            width: 80%;
        }
    </style>
@extends('layouts.admin_dashboard')
@section('content')
    <!-- END: Left Aside -->
        <div class="m-grid__item m-grid__item--fluid m-wrapper">
            <!-- BEGIN: Subheader -->
            <div class="m-subheader">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="m-page-title ">
                            <a href="{{ url('/admin/projects')}}">Projects</a>
                        </h3>
                    </div>
                </div>
            </div>
            @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert"
                     style="display: block; padding: 10px; margin:27px;">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                    <p class="message">
                        {{session('status')}}
                    </p>
                </div>@endif
            <div class="m-portlet m-portlet--rounded view_block">
                <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" method="post"
                      action="{{route('projects.update', $project->id)}}"
                      enctype="multipart/form-data">
                    {{method_field('PUT')}}
                    @include('projects._form')
                </form>
            </div>
            <!-- end:: Body -->
            <!-- begin::Scroll Top -->
            <div class="m-scroll-top m-scroll-top--skin-top" data-toggle="m-scroll-top" data-scroll-offset="500"
                 data-scroll-speed="300">
                <i class="la la-arrow-up"></i>
            </div>
        </div>
        <!-- end::Scroll Top -->
@endsection

typo3_grau_04/resources/views/projects/index.blade.php
<!DOCTYPE html>
<html lang="en">
<!-- begin::Head -->
<head>
    <meta charset="utf-8"/>
    <title>
        Argon | Festanstellung
    </title>
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__rendered .select2-search__field {
            width: 125px !important;
        }
        .m-grid.m-grid--ver-desktop.m-grid--desktop > .m-grid__item.m-grid__item--fluid {
            flex: none !important;
            width: 80%;
        }
    </style>
@extends('layouts.admin_dashboard')
@section('content')
    <!-- END: Left Aside -->
        <div class="m-grid__item m-grid__item--fluid m-wrapper">
            <!-- BEGIN: Subheader -->
            <div class="m-subheader">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="m-page-title ">
                            <a href="{{ url('/admin/projects')}}">Projects</a>
                        </h3>
                    </div>
                </div>
            </div>
            @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert"
                     style="display: block; padding: 10px; margin:27px;">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                    <p class="message">
                        {{session('status')}}
                    </p>
                </div>@endif
            <div class="m-portlet m-portlet--rounded view_block">
                <a  href="/admin/kandidaten" class="pull-right btn btn-info">Back</a>
                <a  href="{{route('projects.create')}}" class="pull-right btn btn-primary" style="margin-right: 20px;">Add project</a>
                <br>
                <br>
                <br>
                <table class="table table-bordered" style="width: 100%;">
                    <tr>
                        <th class="text-center" style="width: 100px;">#</th>
                        <th>Name</th>
                        <th style="width: 150px;"></th>
                    </tr>
                    @foreach($projects as $i => $project)
                        <tr style="background-color: #{{$i%2?'fafafa':'afafaf'}}">
                            <td class="text-center">{{$project->id}}</td>
                            <td>{{$project->name}}</td>
                            <td class="text-center">
                                <a href="{{route('projects.edit', $project)}}">Edit</a>
                                /
                                <a class="delete-project" onclick="$(this).next().submit(); return false;" href="#">Delete</a>
                                <form action="{{route('projects.destroy', $project)}}" method="post">
                                    {{method_field('DELETE')}}
                                    {{csrf_field()}}
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
            <!-- end:: Body -->

            <!-- begin::Scroll Top -->
            <div class="m-scroll-top m-scroll-top--skin-top" data-toggle="m-scroll-top" data-scroll-offset="500"
                 data-scroll-speed="300">
                <i class="la la-arrow-up"></i>
            </div>
        </div>
        <!-- end::Scroll Top -->
@endsection